function (configure_build_folder BUILD_FOLDER_NAME)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/lib PARENT_SCOPE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/lib PARENT_SCOPE)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/bin PARENT_SCOPE)

    if (CMAKE_BUILD_TYPE MATCHES Debug)
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/lib PARENT_SCOPE)
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/lib PARENT_SCOPE)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/bin PARENT_SCOPE)
    elseif (CMAKE_BUILD_TYPE MATCHES Release)
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/lib PARENT_SCOPE)
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/lib PARENT_SCOPE)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/${BUILD_FOLDER_NAME}/bin PARENT_SCOPE)
    endif()
endfunction()
function(configure_lexer_and_bison BISON_INPUT FLEX_INPUT OUT_BISON OUT_FLEX)
    # Find Bison and Flex
    find_package(BISON REQUIRED)
    find_package(FLEX REQUIRED)

    file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bison)
    file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/flex)

    bison_target(Parser ${BISON_INPUT} ${CMAKE_CURRENT_BINARY_DIR}/bison/grammar.tab.cc
            DEFINES_FILE ${CMAKE_CURRENT_BINARY_DIR}/bison/grammar.tab.h
    )
    flex_target(Lexer ${FLEX_INPUT} ${CMAKE_CURRENT_BINARY_DIR}/flex/lex.yy.cc
            COMPILE_FLAGS "--c++"
    )
    add_flex_bison_dependency(Lexer Parser)

    set(${OUT_BISON} ${BISON_Parser_OUTPUTS} PARENT_SCOPE)
    set(${OUT_FLEX}  ${FLEX_Lexer_OUTPUTS}  PARENT_SCOPE)

endfunction()